refactoring, modularization, rst parser, rst documentation, sphinx

diff --git a/sanei b/sanei
--- a/sanei
+++ b/sanei
@@ -1,7 +1,37 @@
 #!/bin/bash
+# SANEi
+# =====
+# .. module:: sanei
+#    :synopsis: A collection of bash scripts.
+#    :platform: raring
+# .. moduleauthor:: Bazyli Brzoska <bazyli.brzoska@gmail.com>
+#
+# :Description: (todo)
+# :Dependencies: - sanei
+#                - apt:software-properties-common
+#                - apt:git
+#                - apt:ufw
+#                - apt:dialog
+#
+# Arguments
+# +++++++++
+#
+# .. cmdoption:: action
+#
+#    Specify the action of the SANEi module.
+#
+# Variables
+# +++++++++
+#
+# .. envvar:: SCRIPT_DIR
+#
+#    The installation directory of SANEi.
+# 
+# Code
+# ++++
 SCRIPT_DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"
-if ! source $SCRIPT_DIR/functions.sh; then
-    echo "ERROR: Missing functions file."
+if ! source "$SCRIPT_DIR/modules/sanei/lib/sanei.sh"; then
+    echo "ERROR: Missing library file."
     exit 1
 fi
 if [[ ! $(whoami) == "root" ]]; then
@@ -9,102 +39,4 @@ if [[ ! $(whoami) == "root" ]]; then
     exit 1
 fi
 
-# TODO: make it into a function call
-case ${ARGUMENTS[0]} in
-    "install" )
-        sanei_install ${ARGUMENTS[@]:1:${#ARGUMENTS[@]}}
-        ;;
-    "update" )
-        sanei_update ${ARGUMENTS[@]:1:${#ARGUMENTS[@]}}
-        ;;
-    "updateall" )
-        sanei_updateall
-        ;;
-    "override" )
-        sanei_override
-        ;;
-    "setinstalled" )
-        set_installed ${ARGUMENTS[1]}
-        ;;
-    "config" )
-        case ${ARGUMENTS[1]} in
-            "list" )
-                print_config | sort
-                ;;
-            "setshared" )
-                if [[ ! -z ${ARGUMENTS[2]} ]]; then
-                    store_shared_config ${ARGUMENTS[@]:2:${#ARGUMENTS[@]}}
-                fi
-                ;;
-            "setlocal" )
-                if [[ ! -z ${ARGUMENTS[2]} ]]; then
-                    store_local_config ${ARGUMENTS[@]:2:${#ARGUMENTS[@]}}
-                fi
-                ;;
-            * )
-                echo "Available commands are:"
-                echo "  config list"
-                echo "  config setshared [VAR] [VALUE]"
-                echo "  config setlocal [VAR] [VALUE]"
-                ;;
-        esac
-        ;;
-    "list" )
-        sanei_list_modules_with_status
-        ;;
-    "module" )
-        sanei_invoke_module_script ${ARGUMENTS[@]:1:${#ARGUMENTS[@]}}
-        ;;
-    "selfupdate" )
-        sanei_invoke_module_script selfupdate do
-        ;;
-    "push" )
-        sanei_invoke_module_script selfupdate send # TODO: cd /shared
-        ;;
-    "lxc" )
-        case ${ARGUMENTS[1]} in
-            "create" )
-                REINSTALL=true
-                __SPECIAL=true
-                sanei_install lxc-template ${ARGUMENTS[@]:2:${#ARGUMENTS[@]}}
-                ;;
-            "updateall" )
-                sanei_updateall_containers
-                ;;
-            * )
-                echo "Available commands are:"
-                echo "  lxc updateall"
-                echo "  lxc create TEMPLATE_NAME"
-                ;;
-        esac
-        ;;
-    # NOT IMPLEMENTED YET:
-    "overridelxc" )
-        todo "override lxc"
-        exit 0;
-        sanei_overridelxc
-        ;;
-    "configure" )
-        todo "changing configuration"
-        exit 0;
-        sanei_configure
-        ;;
-    * )
-        echo "Welcome to SANEi 0.92"
-        echo
-        echo "Available commands are:"
-        echo "  install"
-        echo "  update [MODULE]"
-        echo "  updateall"
-        echo "  setinstalled"
-        echo "  override"
-        echo "  list"
-        echo "  config list"
-        echo "  config setshared [VAR] [VALUE]"
-        echo "  config setlocal [VAR] [VALUE]"
-        echo "  module [MODULE] [OPERATION] [PARAMETERS]"
-        echo "  lxc updateall"
-        echo "  lxc create [TEMPLATE_NAME]"
-        echo "  selfupdate"
-        ;;
-esac
+sanei_invoke_module_script sanei ${ARGUMENTS[@]}
